[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "motie-wijzer"
version = "0.1.0"
dependencies = [
  "typer>=0.14.0"
]

[project.scripts]
motiewijzer = "motiewijzer.__main__:main"

[tool.poetry]
classifiers = ["Private :: Do Not Upload",]
